### ISSUE TITLE
[BUG] Unknown ERROR When raising user_space_size limit

### ISSUE THREAD

**Issue by lz18064638846** [occlum/occlum#403] opened 2021-04-16 03:07 UTC
When I try to use larger user_space for java applications, this error occurs.
Detail like this: [ERROR] occlum-pal: Failed to do ECall: occlum_ecall_broadcast_interrupts with error code 0x1003: Unknown SGX error (line 27, file src/pal_interrupt_thread.c) 

Is there any inexplict limitaion for user_space_size when running occlum? If not, how to fix this bug?

**Comment by guzongmin** [comment] 2021-04-16 03:12
@lz18064638846 Can you please share me the Occlum.json of your project? I think it may be caused by the limited thread number. You could try to enlarge the max_num_of_threads.

**Comment by lz18064638846** [comment] 2021-04-16 03:18
> @lz18064638846 Can you please share me the Occlum.json of your project? I think it may be caused by the limited thread number. You could try to enlarge the max_num_of_threads.

Thanks a lot, it works. Could I ask the reason why max thread number affect this? My applications won't use more threads because the user space raise.

**Comment by guzongmin** [comment] 2021-04-16 03:24
@lz18064638846 JVM would create a lot of threads, even if your application is not a multi-thread one.

**Comment by guzongmin** [comment] 2021-04-16 05:31
Close this issue, since the solution works well.

**Closed by guzongmin** 2021-04-16 05:31 UTC
