### ISSUE TITLE
Run error about java demo

### ISSUE THREAD

**Issue by sqq0216** [occlum/occlum#132] opened 2020-09-15 09:19 UTC
I run the java demo in hardware mode, Reproducing steps:
```
$cd /root/demos/java
$occlum-javac ./hello_world/Main.java
$./run_java_on_occlum.sh hello
```
but I get an error:
```
root@8334a1441cf4:~/demos/java# occlum-javac ./hello_world/Main.java
root@8334a1441cf4:~/demos/java# ./run_java_on_occlum.sh hello
/root/demos/java/occlum_instance initialized as an Occlum instance
Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Init Enclave Successful 502511173634!
Building libOS...
EXPORT => OCCLUM_BUILTIN_CONF_FILE_MAC = 02-6f-95-72-49-30-1b-74-80-ea-57-d1-3b-a1-2a-c6
EXPORT => OCCLUM_BUILTIN_VM_USER_SPACE_SIZE = 1468006400
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <HeapMaxSize>67108864</HeapMaxSize>
    <TCSNum>64</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>1468006400</ReservedMemMaxSize>
    <ReservedMemMinSize>1468006400</ReservedMemMinSize>
    <ReservedMemInitSize>1468006400</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 64, tcs_max_num 64, tcs_min_pool 1
The required memory is 1605533696B.
The required memory is 0x5fb28000, 1567904 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run JVM hello
thread '<unnamed>' panicked at 'assertion failed: sgx_status == sgx_status_t::SGX_SUCCESS && retval == 0', src/vm/vm_manager.rs:819:13
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: sgx_tstd::panicking::begin_panic
   6: occlum_libos_core_rs::vm::vm_manager::VMManager::mmap
   7: occlum_libos_core_rs::vm::process_vm::ProcessVM::mmap
   8: occlum_libos_core_rs::vm::do_mmap
   9: occlum_libos_core_rs::syscall::dispatch_syscall
  10: occlum_libos_core_rs::syscall::do_syscall
  11: occlum_syscall
  12: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 191:   189 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```
I don't know what is wrong, I use ubuntu16.04,and occlum/occlum:0.15.1-ubuntu18.04 images,Could someone give me some suggestions?

**Comment by liqinggd** [comment] 2020-09-16 06:30
@sqq0216 , I cannot reproduce the issue, it seems to fail to do Ocall, have you tried to run a simple C program, can it work fine?

**Comment by sqq0216** [comment] 2020-09-16 06:33
yes, I have ran a C program ,It's ok. But the java demo run error.

**Comment by jessehui** [comment] 2020-09-17 08:45
Looks like the mprotect failed. Can you clone the repo and run a make test to see if mprotect works in your environment? mprotect is tested in test/mmap. Please refer to [this](https://github.com/occlum/occlum#how-to-build-and-install) and run a make test.

**Comment by guzongmin** [comment] 2021-07-30 08:25
No more discussions, close it.

**Closed by guzongmin** 2021-07-30 08:25 UTC
